---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  tags:
    - update-cache

- name: Install "{{ cli_dependencies_packages }}" dependencies
  apt:
    name: "{{ cli_dependencies_packages }}"
    state: present
    force: true
  tags:
    - install

- name: Install {{ cli_package }}
  pip:
    name: "{{ cli_package }}"
    state: present
  tags:
    - install
